title: Steve's Learning Blog Page
author: Steve Teece
email: sgteece@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was created while doing the Githum Learning tutorials. It is not intended for actual use or blog posts.

# social links
github_username:  SteveTeece

show_excerpts: true # set to false to remove excerpts on the homepage

theme: architecht
